name: Main

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: |
          flutter config --enable-macos-desktop && cd example
          flutter packages get && flutter build macos

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: |
          flutter config --enable-windows-desktop && cd example
          flutter packages get && flutter build windows